### ISSUE TITLE
How to save the purchase order?

### ISSUE THREAD

**Issue by eArabic** [anshumanb/shopping-cart-php#1]
Hello
Thank you very much, I am a novice learning php programming
How to save the purchase order and save buyer's name, address and phone number to communicate with him.
Please, what is the way to save data in a text file or database?
Thank you so much

**Comment by anshumanb** [comment]
Hi, I'm a novice PHP programmer myself. You're best served looking up online on how to save data to a database, text file etc. Try something like https://davidwalsh.name/basic-php-file-handling-create-open-read-write-append-close-delete
Good luck!
